modLoader="javafml" #mandatory
loaderVersion="[42,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
    modId="compactmachines"
    version="${file.jarVersion}"
    displayName="Compact Machines 5"
    authors="Davenonymous, RobotGryphon" #optional
    description="It's all so tiny!"

    issueTrackerURL="https://github.com/CompactMods/CompactMachines/issues"

    #updateJSONURL="http://myurl.me/" #optional
    displayURL="https://compactmods.dev"

    # A file name (in the root of the mod JAR) containing a logo for display
    # logoFile="examplemod.png" #optional

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.compactmachines]] #optional
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.compactmachines]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,)"
    ordering="NONE"
    side="BOTH"