modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license = "MIT"

${additional_access_transformers}
[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "compactmachines.mixins.json"

[[mods]]
modId = "compactmachines"
version = "${mod_version}"
displayName = "Compact Machines"
authors = "Davenonymous, RobotGryphon"
description = "It's all so tiny!"
featureFlags="META-INF/feature_flags.json"
issueTrackerURL = "https://github.com/CompactMods/CompactMachines/issues"
displayURL = "https://compactmods.dev"

[[dependencies.compactmachines]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.compactmachines]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"