[versions]
gander = "[0.2.3]"
feather = "[0.1.8]"

[versions.spatial]
require = "[0.2.0, 0.3)"
prefer = "0.2.1"

[libraries.feather]
module = "dev.compactmods:feather"
version.ref = "feather"

[libraries.spatial]
module = "dev.compactmods:spatial"
version.ref = "spatial"

[libraries.ganderCore]
module = "dev.compactmods.gander:core"
version.ref = "gander"

[libraries.ganderLevels]
module = "dev.compactmods.gander:levels"
version.ref = "gander"

[libraries.ganderRendering]
module = "dev.compactmods.gander:rendering"
version.ref = "gander"

[libraries.ganderUI]
module = "dev.compactmods.gander:ui"
version.ref = "gander"

[bundles]
gander = ["ganderCore", "ganderLevels", "ganderRendering", "ganderUI"]