[versions]
jnanoid = "[2.0.0, 3)"

# Get versions from https://parchmentmc.org/docs/getting-started
parchmentMC = "1.21.9"
parchment = "2025.10.05"

[libraries.jnanoid]
module = "com.aventrix.jnanoid:jnanoid"
version.ref = "jnanoid"

[libraries.curios]
module = "top.theillusivec4.curios:curios-neoforge"
version = "9.2.2+1.21.1"