[versions]
jei = "17.3.0.49"

# Jade
[libraries.jade]
module = "curse.maven:jade-324717"
version = "5109393"

# Just Enough Items
[libraries.jeiCommon]
module = "mezz.jei:jei-1.20.4-common-api"
version.ref = "jei"

[libraries.jeiNeo]
module = "mezz.jei:jei-1.20.4-neoforge-api"
version.ref = "jei"

[bundles]
jei = ["jeiCommon", "jeiNeo"]

# Kube JS
[libraries.kubeJS]
module = "dev.latvian.mods:kubejs-neoforge"
version = "2101.7.2-build.247"

[libraries.rhino]
module = "dev.latvian.mods:rhino"
version = "2101.2.6-build.66"