[versions]
# https://maven.blamejared.com/mezz/jei/
jei = "24.0.0.2"

# Jade
[libraries.jade]
module = "curse.maven:jade-324717"
version = "6853386"

# Just Enough Items
[libraries.jeiCommon]
module = "mezz.jei:jei-1.21.8-common-api"
version.ref = "jei"

[libraries.jeiNeo]
module = "mezz.jei:jei-1.21.8-neoforge-api"
version.ref = "jei"

[bundles]
jei = ["jeiCommon", "jeiNeo"]

# Kube JS
[libraries.kubeJS]
module = "dev.latvian.mods:kubejs-neoforge"
version = "2101.7.2-build.247"

[libraries.rhino]
module = "dev.latvian.mods:rhino"
version = "2101.2.6-build.66"