[versions]
neoforge = "21.8.45"
mdg = "2.0.107"
neoforgeRange = { require = "[21.8.45,)", prefer = "21.8.45" }
neoform = "1.21.8-20250717.133445"

[libraries.testframework]
module = "net.neoforged:testframework"
version.ref = "neoforge"

[plugins.moddev]
id = "net.neoforged.moddev"
version.ref = "mdg"
