[versions]
neoforge = "21.10.16-beta"
mdg = "2.0.112"
neoforgeRange = { require = "[21.10.1-beta,)", prefer = "21.10.16-beta" }
neoform = "1.21.10-20251010.172816"

[libraries.testframework]
module = "net.neoforged:testframework"
version.ref = "neoforge"

[plugins.moddev]
id = "net.neoforged.moddev"
version.ref = "mdg"
