---
name: Bug Report - CM4 (1.18.x)
about: Submit a report for Compact Machines 4, for 1.18.x
title: ''
labels: 1.18, bug, unverified
assignees: ''

---

**READ THIS FIRST, THEN REMOVE**:
> Do not create an issue if you have not tried fixing it by using the latest version of the mod!
> If you are using Optifine, we request you remove Optifine and try to reproduce your issue before submitting this report.
> Anything in a quote (it looks like this block, or has a ">" at the start of the line) are instructions. Please remove them before submitting the report.

**Description of the problem including expected versus actual behavior:**
> I attempted to do X, but Y happened instead.

### Mod and Forge Versions
> Do not use "latest" for versions. Be exact; it helps us track down the issue more accurately.

**Mod Version:** 4.0.0
**Forge version:** 1.18.1 - 39.0.0

### Crash Information
**Link to Crashlog**: [here](url)
**Screenshot (if possible)**: [here](url)

**Steps to reproduce:**
1. Step 1
2. Step 2
3. Step 3
