name: Bug Report - Compact Machines 3
description: Submit a report for Compact Machines 3
labels:
  - 1.12
  - triage
  - bug
  - unverified
assignees: []
body:
  - type: markdown
    attributes:
      value: "*Please do not create an issue if you have not tried fixing it by using the latest version of the mod!*"

  - type: checkboxes
    attributes:
      label: I am not using performance mods.
      description: We request you remove performance mods and try to reproduce your issue before submitting this report. Examples include Optifine, Lithium, Sodium, and BetterFPS.
      options:
        - label: Confirm
          required: true

  - type: textarea
    attributes: 
      label: Description
      description: Description of the problem, including expected versus actual behavior.
      placeholder: I attempted to do X, but Y happened instead.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Mod and Forge Versions"
      
  - type: markdown
    attributes:
      value: > 
        *Do not use 'latest' for versions. Be exact; it helps us track down the issue accurately.*
        If you need help finding the mod version, check the mods menu, accessible from the Main Menu of the game.

  - type: input
    attributes:
      label: Mod Version
      placeholder: CM3-3.0.18-b278
    validations:
      required: true

  - type: input
    attributes:
      label: Forge Version
      placeholder: 1.12.2 - 14.23.5.2854
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Crash Information"

  - type: input
    attributes:
      label: Link to Crashlog
      placeholder: pastebin/gist/etc.

  - type: textarea
    attributes:
      label: Screenshot (if available)
      description: If you have an image, you can attach it by dragging and dropping it from your file browser to the text area here.

  - type: textarea
    attributes:
      label: How to reproduce
      description: "How do you trigger this bug?"
      value: |
        1.
        2.
        3.
    validations:
      required: true
