name: Data Generation

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  datagen:
    name: Data Generators
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Data Generation
        run: ./gradlew :neoforge-datagen:runData
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Additional Access Transformers
        run: ./gradlew :neoforge-main:copyAdditionalAccessTransformers
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store Built Assets
        uses: actions/upload-artifact@v5
        with:
          name: generated-data
          path: neoforge-main/src/generated/resources

      - name: Store Compiled Core
        uses: actions/upload-artifact@v5
        with:
          name: build-core
          path: core-api/build

      - name: Store Compiled
        uses: actions/upload-artifact@v5
        with:
          name: build-main
          path: neoforge-main/build